//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.23 at 12:19:01 PM EDT 
//


package gov.nara.das.common.db.das.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="recordGroupArray">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="recordGroup" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="dasItemType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="jobId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                             &lt;element name="sqsMessageId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="chunkingId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="messageIndex" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                             &lt;element name="beginCongress" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="termName" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="endCongress" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="termName" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="dataControlGroup">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="groupCd" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="groupId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="groupName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="guid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="isUnderEdit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="recordGroupNumber" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                             &lt;element name="dateNote" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="scopeAndContentNote" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="specialProjectArray">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="specialProject" maxOccurs="unbounded" minOccurs="0">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="termName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "recordGroupArray"
})
@XmlRootElement(name = "import")
public class Import {

    @XmlElement(required = true)
    protected Import.RecordGroupArray recordGroupArray;

    /**
     * Gets the value of the recordGroupArray property.
     * 
     * @return
     *     possible object is
     *     {@link Import.RecordGroupArray }
     *     
     */
    public Import.RecordGroupArray getRecordGroupArray() {
        return recordGroupArray;
    }

    /**
     * Sets the value of the recordGroupArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link Import.RecordGroupArray }
     *     
     */
    public void setRecordGroupArray(Import.RecordGroupArray value) {
        this.recordGroupArray = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="recordGroup" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="dasItemType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="jobId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                   &lt;element name="sqsMessageId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="chunkingId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="messageIndex" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *                   &lt;element name="beginCongress" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="termName" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="endCongress" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="termName" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="dataControlGroup">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="groupCd" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="groupId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="groupName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="guid" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="isUnderEdit" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="recordGroupNumber" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                   &lt;element name="dateNote" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="scopeAndContentNote" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="specialProjectArray">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="specialProject" maxOccurs="unbounded" minOccurs="0">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="termName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "recordGroup"
    })
    public static class RecordGroupArray {

        protected List<Import.RecordGroupArray.RecordGroup> recordGroup;

        /**
         * Gets the value of the recordGroup property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the recordGroup property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRecordGroup().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Import.RecordGroupArray.RecordGroup }
         * 
         * 
         */
        public List<Import.RecordGroupArray.RecordGroup> getRecordGroup() {
            if (recordGroup == null) {
                recordGroup = new ArrayList<Import.RecordGroupArray.RecordGroup>();
            }
            return this.recordGroup;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="dasItemType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="jobId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *         &lt;element name="sqsMessageId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="chunkingId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="messageIndex" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
         *         &lt;element name="beginCongress" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="termName" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="endCongress" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="termName" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="dataControlGroup">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="groupCd" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="groupId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="groupName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="guid" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="isUnderEdit" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="recordGroupNumber" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="dateNote" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="scopeAndContentNote" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="specialProjectArray">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="specialProject" maxOccurs="unbounded" minOccurs="0">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="termName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "dasItemType",
            "jobId",
            "sqsMessageId",
            "chunkingId",
            "messageIndex",
            "beginCongress",
            "endCongress",
            "dataControlGroup",
            "guid",
            "title",
            "isUnderEdit",
            "recordGroupNumber",
            "dateNote",
            "scopeAndContentNote",
            "specialProjectArray"
        })
        public static class RecordGroup {

            protected String dasItemType;
            protected Integer jobId;
            protected String sqsMessageId;
            protected String chunkingId;
            protected Integer messageIndex;
            protected Import.RecordGroupArray.RecordGroup.BeginCongress beginCongress;
            protected Import.RecordGroupArray.RecordGroup.EndCongress endCongress;
            @XmlElement(required = true)
            protected Import.RecordGroupArray.RecordGroup.DataControlGroup dataControlGroup;
            @XmlElement(required = true)
            protected String guid;
            @XmlElement(required = true)
            protected String title;
            @XmlElement(required = true)
            protected String isUnderEdit;
            protected short recordGroupNumber;
            @XmlElement(required = true)
            protected String dateNote;
            @XmlElement(required = true)
            protected String scopeAndContentNote;
            @XmlElement(required = true)
            protected Import.RecordGroupArray.RecordGroup.SpecialProjectArray specialProjectArray;

            /**
             * Gets the value of the dasItemType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDasItemType() {
                return dasItemType;
            }

            /**
             * Sets the value of the dasItemType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDasItemType(String value) {
                this.dasItemType = value;
            }

            /**
             * Gets the value of the jobId property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getJobId() {
                return jobId;
            }

            /**
             * Sets the value of the jobId property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setJobId(Integer value) {
                this.jobId = value;
            }

            /**
             * Gets the value of the sqsMessageId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSqsMessageId() {
                return sqsMessageId;
            }

            /**
             * Sets the value of the sqsMessageId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSqsMessageId(String value) {
                this.sqsMessageId = value;
            }

            /**
             * Gets the value of the chunkingId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getChunkingId() {
                return chunkingId;
            }

            /**
             * Sets the value of the chunkingId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setChunkingId(String value) {
                this.chunkingId = value;
            }

            /**
             * Gets the value of the messageIndex property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getMessageIndex() {
                return messageIndex;
            }

            /**
             * Sets the value of the messageIndex property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setMessageIndex(Integer value) {
                this.messageIndex = value;
            }

            /**
             * Gets the value of the beginCongress property.
             * 
             * @return
             *     possible object is
             *     {@link Import.RecordGroupArray.RecordGroup.BeginCongress }
             *     
             */
            public Import.RecordGroupArray.RecordGroup.BeginCongress getBeginCongress() {
                return beginCongress;
            }

            /**
             * Sets the value of the beginCongress property.
             * 
             * @param value
             *     allowed object is
             *     {@link Import.RecordGroupArray.RecordGroup.BeginCongress }
             *     
             */
            public void setBeginCongress(Import.RecordGroupArray.RecordGroup.BeginCongress value) {
                this.beginCongress = value;
            }

            /**
             * Gets the value of the endCongress property.
             * 
             * @return
             *     possible object is
             *     {@link Import.RecordGroupArray.RecordGroup.EndCongress }
             *     
             */
            public Import.RecordGroupArray.RecordGroup.EndCongress getEndCongress() {
                return endCongress;
            }

            /**
             * Sets the value of the endCongress property.
             * 
             * @param value
             *     allowed object is
             *     {@link Import.RecordGroupArray.RecordGroup.EndCongress }
             *     
             */
            public void setEndCongress(Import.RecordGroupArray.RecordGroup.EndCongress value) {
                this.endCongress = value;
            }

            /**
             * Gets the value of the dataControlGroup property.
             * 
             * @return
             *     possible object is
             *     {@link Import.RecordGroupArray.RecordGroup.DataControlGroup }
             *     
             */
            public Import.RecordGroupArray.RecordGroup.DataControlGroup getDataControlGroup() {
                return dataControlGroup;
            }

            /**
             * Sets the value of the dataControlGroup property.
             * 
             * @param value
             *     allowed object is
             *     {@link Import.RecordGroupArray.RecordGroup.DataControlGroup }
             *     
             */
            public void setDataControlGroup(Import.RecordGroupArray.RecordGroup.DataControlGroup value) {
                this.dataControlGroup = value;
            }

            /**
             * Gets the value of the guid property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGuid() {
                return guid;
            }

            /**
             * Sets the value of the guid property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGuid(String value) {
                this.guid = value;
            }

            /**
             * Gets the value of the title property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTitle() {
                return title;
            }

            /**
             * Sets the value of the title property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTitle(String value) {
                this.title = value;
            }

            /**
             * Gets the value of the isUnderEdit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIsUnderEdit() {
                return isUnderEdit;
            }

            /**
             * Sets the value of the isUnderEdit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIsUnderEdit(String value) {
                this.isUnderEdit = value;
            }

            /**
             * Gets the value of the recordGroupNumber property.
             * 
             */
            public short getRecordGroupNumber() {
                return recordGroupNumber;
            }

            /**
             * Sets the value of the recordGroupNumber property.
             * 
             */
            public void setRecordGroupNumber(short value) {
                this.recordGroupNumber = value;
            }

            /**
             * Gets the value of the dateNote property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDateNote() {
                return dateNote;
            }

            /**
             * Sets the value of the dateNote property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDateNote(String value) {
                this.dateNote = value;
            }

            /**
             * Gets the value of the scopeAndContentNote property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getScopeAndContentNote() {
                return scopeAndContentNote;
            }

            /**
             * Sets the value of the scopeAndContentNote property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setScopeAndContentNote(String value) {
                this.scopeAndContentNote = value;
            }

            /**
             * Gets the value of the specialProjectArray property.
             * 
             * @return
             *     possible object is
             *     {@link Import.RecordGroupArray.RecordGroup.SpecialProjectArray }
             *     
             */
            public Import.RecordGroupArray.RecordGroup.SpecialProjectArray getSpecialProjectArray() {
                return specialProjectArray;
            }

            /**
             * Sets the value of the specialProjectArray property.
             * 
             * @param value
             *     allowed object is
             *     {@link Import.RecordGroupArray.RecordGroup.SpecialProjectArray }
             *     
             */
            public void setSpecialProjectArray(Import.RecordGroupArray.RecordGroup.SpecialProjectArray value) {
                this.specialProjectArray = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="termName" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "termName"
            })
            public static class BeginCongress {

                protected byte termName;

                /**
                 * Gets the value of the termName property.
                 * 
                 */
                public byte getTermName() {
                    return termName;
                }

                /**
                 * Sets the value of the termName property.
                 * 
                 */
                public void setTermName(byte value) {
                    this.termName = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="groupCd" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="groupId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="groupName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "groupCd",
                "groupId",
                "groupName"
            })
            public static class DataControlGroup {

                @XmlElement(required = true)
                protected String groupCd;
                @XmlElement(required = true)
                protected String groupId;
                @XmlElement(required = true)
                protected String groupName;

                /**
                 * Gets the value of the groupCd property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getGroupCd() {
                    return groupCd;
                }

                /**
                 * Sets the value of the groupCd property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setGroupCd(String value) {
                    this.groupCd = value;
                }

                /**
                 * Gets the value of the groupId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getGroupId() {
                    return groupId;
                }

                /**
                 * Sets the value of the groupId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setGroupId(String value) {
                    this.groupId = value;
                }

                /**
                 * Gets the value of the groupName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getGroupName() {
                    return groupName;
                }

                /**
                 * Sets the value of the groupName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setGroupName(String value) {
                    this.groupName = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="termName" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "termName"
            })
            public static class EndCongress {

                protected byte termName;

                /**
                 * Gets the value of the termName property.
                 * 
                 */
                public byte getTermName() {
                    return termName;
                }

                /**
                 * Sets the value of the termName property.
                 * 
                 */
                public void setTermName(byte value) {
                    this.termName = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="specialProject" maxOccurs="unbounded" minOccurs="0">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="termName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "specialProject"
            })
            public static class SpecialProjectArray {

                protected List<Import.RecordGroupArray.RecordGroup.SpecialProjectArray.SpecialProject> specialProject;

                /**
                 * Gets the value of the specialProject property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the specialProject property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getSpecialProject().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link Import.RecordGroupArray.RecordGroup.SpecialProjectArray.SpecialProject }
                 * 
                 * 
                 */
                public List<Import.RecordGroupArray.RecordGroup.SpecialProjectArray.SpecialProject> getSpecialProject() {
                    if (specialProject == null) {
                        specialProject = new ArrayList<Import.RecordGroupArray.RecordGroup.SpecialProjectArray.SpecialProject>();
                    }
                    return this.specialProject;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="termName" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "termName"
                })
                public static class SpecialProject {

                    @XmlElement(required = true)
                    protected String termName;

                    /**
                     * Gets the value of the termName property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getTermName() {
                        return termName;
                    }

                    /**
                     * Sets the value of the termName property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setTermName(String value) {
                        this.termName = value;
                    }

                }

            }

        }

    }

}
