//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.23 at 12:19:01 PM EDT 
//


package gov.nara.das.common.db.das.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nara.das.common.db.das.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nara.das.common.db.das.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Import }
     * 
     */
    public Import createImport() {
        return new Import();
    }

    /**
     * Create an instance of {@link Import.RecordGroupArray }
     * 
     */
    public Import.RecordGroupArray createImportRecordGroupArray() {
        return new Import.RecordGroupArray();
    }

    /**
     * Create an instance of {@link Import.RecordGroupArray.RecordGroup }
     * 
     */
    public Import.RecordGroupArray.RecordGroup createImportRecordGroupArrayRecordGroup() {
        return new Import.RecordGroupArray.RecordGroup();
    }

    /**
     * Create an instance of {@link Import.RecordGroupArray.RecordGroup.SpecialProjectArray }
     * 
     */
    public Import.RecordGroupArray.RecordGroup.SpecialProjectArray createImportRecordGroupArrayRecordGroupSpecialProjectArray() {
        return new Import.RecordGroupArray.RecordGroup.SpecialProjectArray();
    }

    /**
     * Create an instance of {@link Import.RecordGroupArray.RecordGroup.BeginCongress }
     * 
     */
    public Import.RecordGroupArray.RecordGroup.BeginCongress createImportRecordGroupArrayRecordGroupBeginCongress() {
        return new Import.RecordGroupArray.RecordGroup.BeginCongress();
    }

    /**
     * Create an instance of {@link Import.RecordGroupArray.RecordGroup.EndCongress }
     * 
     */
    public Import.RecordGroupArray.RecordGroup.EndCongress createImportRecordGroupArrayRecordGroupEndCongress() {
        return new Import.RecordGroupArray.RecordGroup.EndCongress();
    }

    /**
     * Create an instance of {@link Import.RecordGroupArray.RecordGroup.DataControlGroup }
     * 
     */
    public Import.RecordGroupArray.RecordGroup.DataControlGroup createImportRecordGroupArrayRecordGroupDataControlGroup() {
        return new Import.RecordGroupArray.RecordGroup.DataControlGroup();
    }

    /**
     * Create an instance of {@link Import.RecordGroupArray.RecordGroup.SpecialProjectArray.SpecialProject }
     * 
     */
    public Import.RecordGroupArray.RecordGroup.SpecialProjectArray.SpecialProject createImportRecordGroupArrayRecordGroupSpecialProjectArraySpecialProject() {
        return new Import.RecordGroupArray.RecordGroup.SpecialProjectArray.SpecialProject();
    }

}
