//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.23 at 12:19:01 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ui.das.nara.gov/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gov.nara.das.common.db.das.jaxb;
