//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.11.09 at 10:45:43 AM EST 
//


package gov.nara.das.common.db.das.jaxb;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nara.das.common.db.das.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nara.das.common.db.das.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Import }
     * 
     */
    public Import createImport() {
        return new Import();
    }

    /**
     * Create an instance of {@link Import.SeriesArray }
     * 
     */
    public Import.SeriesArray createImportSeriesArray() {
        return new Import.SeriesArray();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series }
     * 
     */
    public Import.SeriesArray.Series createImportSeriesArraySeries() {
        return new Import.SeriesArray.Series();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.DescriptionAuthorArray }
     * 
     */
    public Import.SeriesArray.Series.DescriptionAuthorArray createImportSeriesArraySeriesDescriptionAuthorArray() {
        return new Import.SeriesArray.Series.DescriptionAuthorArray();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.DescriptionAuthorArray.DescriptionAuthor }
     * 
     */
    public Import.SeriesArray.Series.DescriptionAuthorArray.DescriptionAuthor createImportSeriesArraySeriesDescriptionAuthorArrayDescriptionAuthor() {
        return new Import.SeriesArray.Series.DescriptionAuthorArray.DescriptionAuthor();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.DescriptionAuthorArray.DescriptionAuthor.DescriptionDateArray }
     * 
     */
    public Import.SeriesArray.Series.DescriptionAuthorArray.DescriptionAuthor.DescriptionDateArray createImportSeriesArraySeriesDescriptionAuthorArrayDescriptionAuthorDescriptionDateArray() {
        return new Import.SeriesArray.Series.DescriptionAuthorArray.DescriptionAuthor.DescriptionDateArray();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.DigitalObjectArray }
     * 
     */
    public Import.SeriesArray.Series.DigitalObjectArray createImportSeriesArraySeriesDigitalObjectArray() {
        return new Import.SeriesArray.Series.DigitalObjectArray();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.DigitalObjectArray.DigitalObject }
     * 
     */
    public Import.SeriesArray.Series.DigitalObjectArray.DigitalObject createImportSeriesArraySeriesDigitalObjectArrayDigitalObject() {
        return new Import.SeriesArray.Series.DigitalObjectArray.DigitalObject();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.GeneralRecordsTypeArray }
     * 
     */
    public Import.SeriesArray.Series.GeneralRecordsTypeArray createImportSeriesArraySeriesGeneralRecordsTypeArray() {
        return new Import.SeriesArray.Series.GeneralRecordsTypeArray();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.UseRestriction }
     * 
     */
    public Import.SeriesArray.Series.UseRestriction createImportSeriesArraySeriesUseRestriction() {
        return new Import.SeriesArray.Series.UseRestriction();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.AccessRestriction }
     * 
     */
    public Import.SeriesArray.Series.AccessRestriction createImportSeriesArraySeriesAccessRestriction() {
        return new Import.SeriesArray.Series.AccessRestriction();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.SpecialProjectArray }
     * 
     */
    public Import.SeriesArray.Series.SpecialProjectArray createImportSeriesArraySeriesSpecialProjectArray() {
        return new Import.SeriesArray.Series.SpecialProjectArray();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.LanguageArray }
     * 
     */
    public Import.SeriesArray.Series.LanguageArray createImportSeriesArraySeriesLanguageArray() {
        return new Import.SeriesArray.Series.LanguageArray();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.GeneralNoteArray }
     * 
     */
    public Import.SeriesArray.Series.GeneralNoteArray createImportSeriesArraySeriesGeneralNoteArray() {
        return new Import.SeriesArray.Series.GeneralNoteArray();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.CoverageDates }
     * 
     */
    public Import.SeriesArray.Series.CoverageDates createImportSeriesArraySeriesCoverageDates() {
        return new Import.SeriesArray.Series.CoverageDates();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.InclusiveDates }
     * 
     */
    public Import.SeriesArray.Series.InclusiveDates createImportSeriesArraySeriesInclusiveDates() {
        return new Import.SeriesArray.Series.InclusiveDates();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.OnlineResourceArray }
     * 
     */
    public Import.SeriesArray.Series.OnlineResourceArray createImportSeriesArraySeriesOnlineResourceArray() {
        return new Import.SeriesArray.Series.OnlineResourceArray();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.FindingAidArray }
     * 
     */
    public Import.SeriesArray.Series.FindingAidArray createImportSeriesArraySeriesFindingAidArray() {
        return new Import.SeriesArray.Series.FindingAidArray();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.FindingAidArray.FindingAid }
     * 
     */
    public Import.SeriesArray.Series.FindingAidArray.FindingAid createImportSeriesArraySeriesFindingAidArrayFindingAid() {
        return new Import.SeriesArray.Series.FindingAidArray.FindingAid();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.VariantControlNumberArray }
     * 
     */
    public Import.SeriesArray.Series.VariantControlNumberArray createImportSeriesArraySeriesVariantControlNumberArray() {
        return new Import.SeriesArray.Series.VariantControlNumberArray();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.VariantControlNumberArray.VariantControlNumber }
     * 
     */
    public Import.SeriesArray.Series.VariantControlNumberArray.VariantControlNumber createImportSeriesArraySeriesVariantControlNumberArrayVariantControlNumber() {
        return new Import.SeriesArray.Series.VariantControlNumberArray.VariantControlNumber();
    }

    /**
     * Create an instance of {@link Import.RecordGroupArray }
     * 
     */
    public Import.RecordGroupArray createImportRecordGroupArray() {
        return new Import.RecordGroupArray();
    }

    /**
     * Create an instance of {@link Import.RecordGroupArray.RecordGroup }
     * 
     */
    public Import.RecordGroupArray.RecordGroup createImportRecordGroupArrayRecordGroup() {
        return new Import.RecordGroupArray.RecordGroup();
    }

    /**
     * Create an instance of {@link Import.RecordGroupArray.RecordGroup.FindingAidArray }
     * 
     */
    public Import.RecordGroupArray.RecordGroup.FindingAidArray createImportRecordGroupArrayRecordGroupFindingAidArray() {
        return new Import.RecordGroupArray.RecordGroup.FindingAidArray();
    }

    /**
     * Create an instance of {@link Import.RecordGroupArray.RecordGroup.FindingAidArray.FindingAid }
     * 
     */
    public Import.RecordGroupArray.RecordGroup.FindingAidArray.FindingAid createImportRecordGroupArrayRecordGroupFindingAidArrayFindingAid() {
        return new Import.RecordGroupArray.RecordGroup.FindingAidArray.FindingAid();
    }

    /**
     * Create an instance of {@link Import.RecordGroupArray.RecordGroup.SpecialProjectArray }
     * 
     */
    public Import.RecordGroupArray.RecordGroup.SpecialProjectArray createImportRecordGroupArrayRecordGroupSpecialProjectArray() {
        return new Import.RecordGroupArray.RecordGroup.SpecialProjectArray();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.DataControlGroup }
     * 
     */
    public Import.SeriesArray.Series.DataControlGroup createImportSeriesArraySeriesDataControlGroup() {
        return new Import.SeriesArray.Series.DataControlGroup();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.ParentRecordGroup }
     * 
     */
    public Import.SeriesArray.Series.ParentRecordGroup createImportSeriesArraySeriesParentRecordGroup() {
        return new Import.SeriesArray.Series.ParentRecordGroup();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.BeginCongress }
     * 
     */
    public Import.SeriesArray.Series.BeginCongress createImportSeriesArraySeriesBeginCongress() {
        return new Import.SeriesArray.Series.BeginCongress();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.PartyDesignation }
     * 
     */
    public Import.SeriesArray.Series.PartyDesignation createImportSeriesArraySeriesPartyDesignation() {
        return new Import.SeriesArray.Series.PartyDesignation();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.EndCongress }
     * 
     */
    public Import.SeriesArray.Series.EndCongress createImportSeriesArraySeriesEndCongress() {
        return new Import.SeriesArray.Series.EndCongress();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.DescriptionAuthorArray.DescriptionAuthor.DescriptionDateArray.DasDate }
     * 
     */
    public Import.SeriesArray.Series.DescriptionAuthorArray.DescriptionAuthor.DescriptionDateArray.DasDate createImportSeriesArraySeriesDescriptionAuthorArrayDescriptionAuthorDescriptionDateArrayDasDate() {
        return new Import.SeriesArray.Series.DescriptionAuthorArray.DescriptionAuthor.DescriptionDateArray.DasDate();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.DigitalObjectArray.DigitalObject.ObjectType }
     * 
     */
    public Import.SeriesArray.Series.DigitalObjectArray.DigitalObject.ObjectType createImportSeriesArraySeriesDigitalObjectArrayDigitalObjectObjectType() {
        return new Import.SeriesArray.Series.DigitalObjectArray.DigitalObject.ObjectType();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.GeneralRecordsTypeArray.GeneralRecordsType }
     * 
     */
    public Import.SeriesArray.Series.GeneralRecordsTypeArray.GeneralRecordsType createImportSeriesArraySeriesGeneralRecordsTypeArrayGeneralRecordsType() {
        return new Import.SeriesArray.Series.GeneralRecordsTypeArray.GeneralRecordsType();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.UseRestriction.Status }
     * 
     */
    public Import.SeriesArray.Series.UseRestriction.Status createImportSeriesArraySeriesUseRestrictionStatus() {
        return new Import.SeriesArray.Series.UseRestriction.Status();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.AccessRestriction.Status }
     * 
     */
    public Import.SeriesArray.Series.AccessRestriction.Status createImportSeriesArraySeriesAccessRestrictionStatus() {
        return new Import.SeriesArray.Series.AccessRestriction.Status();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.SpecialProjectArray.SpecialProject }
     * 
     */
    public Import.SeriesArray.Series.SpecialProjectArray.SpecialProject createImportSeriesArraySeriesSpecialProjectArraySpecialProject() {
        return new Import.SeriesArray.Series.SpecialProjectArray.SpecialProject();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.LanguageArray.Language }
     * 
     */
    public Import.SeriesArray.Series.LanguageArray.Language createImportSeriesArraySeriesLanguageArrayLanguage() {
        return new Import.SeriesArray.Series.LanguageArray.Language();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.GeneralNoteArray.GeneralNote }
     * 
     */
    public Import.SeriesArray.Series.GeneralNoteArray.GeneralNote createImportSeriesArraySeriesGeneralNoteArrayGeneralNote() {
        return new Import.SeriesArray.Series.GeneralNoteArray.GeneralNote();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.CoverageDates.CoverageStartDate }
     * 
     */
    public Import.SeriesArray.Series.CoverageDates.CoverageStartDate createImportSeriesArraySeriesCoverageDatesCoverageStartDate() {
        return new Import.SeriesArray.Series.CoverageDates.CoverageStartDate();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.CoverageDates.CoverageEndDate }
     * 
     */
    public Import.SeriesArray.Series.CoverageDates.CoverageEndDate createImportSeriesArraySeriesCoverageDatesCoverageEndDate() {
        return new Import.SeriesArray.Series.CoverageDates.CoverageEndDate();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.InclusiveDates.InclusiveStartDate }
     * 
     */
    public Import.SeriesArray.Series.InclusiveDates.InclusiveStartDate createImportSeriesArraySeriesInclusiveDatesInclusiveStartDate() {
        return new Import.SeriesArray.Series.InclusiveDates.InclusiveStartDate();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.InclusiveDates.InclusiveEndDate }
     * 
     */
    public Import.SeriesArray.Series.InclusiveDates.InclusiveEndDate createImportSeriesArraySeriesInclusiveDatesInclusiveEndDate() {
        return new Import.SeriesArray.Series.InclusiveDates.InclusiveEndDate();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.OnlineResourceArray.OnlineResource }
     * 
     */
    public Import.SeriesArray.Series.OnlineResourceArray.OnlineResource createImportSeriesArraySeriesOnlineResourceArrayOnlineResource() {
        return new Import.SeriesArray.Series.OnlineResourceArray.OnlineResource();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.FindingAidArray.FindingAid.Type }
     * 
     */
    public Import.SeriesArray.Series.FindingAidArray.FindingAid.Type createImportSeriesArraySeriesFindingAidArrayFindingAidType() {
        return new Import.SeriesArray.Series.FindingAidArray.FindingAid.Type();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.FindingAidArray.FindingAid.Url }
     * 
     */
    public Import.SeriesArray.Series.FindingAidArray.FindingAid.Url createImportSeriesArraySeriesFindingAidArrayFindingAidUrl() {
        return new Import.SeriesArray.Series.FindingAidArray.FindingAid.Url();
    }

    /**
     * Create an instance of {@link Import.SeriesArray.Series.VariantControlNumberArray.VariantControlNumber.Type }
     * 
     */
    public Import.SeriesArray.Series.VariantControlNumberArray.VariantControlNumber.Type createImportSeriesArraySeriesVariantControlNumberArrayVariantControlNumberType() {
        return new Import.SeriesArray.Series.VariantControlNumberArray.VariantControlNumber.Type();
    }

    /**
     * Create an instance of {@link Import.RecordGroupArray.RecordGroup.BeginCongress }
     * 
     */
    public Import.RecordGroupArray.RecordGroup.BeginCongress createImportRecordGroupArrayRecordGroupBeginCongress() {
        return new Import.RecordGroupArray.RecordGroup.BeginCongress();
    }

    /**
     * Create an instance of {@link Import.RecordGroupArray.RecordGroup.EndCongress }
     * 
     */
    public Import.RecordGroupArray.RecordGroup.EndCongress createImportRecordGroupArrayRecordGroupEndCongress() {
        return new Import.RecordGroupArray.RecordGroup.EndCongress();
    }

    /**
     * Create an instance of {@link Import.RecordGroupArray.RecordGroup.DataControlGroup }
     * 
     */
    public Import.RecordGroupArray.RecordGroup.DataControlGroup createImportRecordGroupArrayRecordGroupDataControlGroup() {
        return new Import.RecordGroupArray.RecordGroup.DataControlGroup();
    }

    /**
     * Create an instance of {@link Import.RecordGroupArray.RecordGroup.FindingAidArray.FindingAid.FileType }
     * 
     */
    public Import.RecordGroupArray.RecordGroup.FindingAidArray.FindingAid.FileType createImportRecordGroupArrayRecordGroupFindingAidArrayFindingAidFileType() {
        return new Import.RecordGroupArray.RecordGroup.FindingAidArray.FindingAid.FileType();
    }

    /**
     * Create an instance of {@link Import.RecordGroupArray.RecordGroup.FindingAidArray.FindingAid.Type }
     * 
     */
    public Import.RecordGroupArray.RecordGroup.FindingAidArray.FindingAid.Type createImportRecordGroupArrayRecordGroupFindingAidArrayFindingAidType() {
        return new Import.RecordGroupArray.RecordGroup.FindingAidArray.FindingAid.Type();
    }

    /**
     * Create an instance of {@link Import.RecordGroupArray.RecordGroup.FindingAidArray.FindingAid.Url }
     * 
     */
    public Import.RecordGroupArray.RecordGroup.FindingAidArray.FindingAid.Url createImportRecordGroupArrayRecordGroupFindingAidArrayFindingAidUrl() {
        return new Import.RecordGroupArray.RecordGroup.FindingAidArray.FindingAid.Url();
    }

    /**
     * Create an instance of {@link Import.RecordGroupArray.RecordGroup.SpecialProjectArray.SpecialProject }
     * 
     */
    public Import.RecordGroupArray.RecordGroup.SpecialProjectArray.SpecialProject createImportRecordGroupArrayRecordGroupSpecialProjectArraySpecialProject() {
        return new Import.RecordGroupArray.RecordGroup.SpecialProjectArray.SpecialProject();
    }

}
